#pragma once

#include "../../SDK/SDK Headers/Entitys.h"

vector< int > iBoxListDefault =
{
	(int)CSGOHitboxID::HITBOX_HEAD,
	(int)CSGOHitboxID::HITBOX_NECK,
	(int)CSGOHitboxID::HITBOX_CHEST,
	(int)CSGOHitboxID::HITBOX_PELVIS,
};

vector< int > iBoxListSafety =
{
	(int)CSGOHitboxID::HITBOX_HEAD,
	(int)CSGOHitboxID::HITBOX_LEFT_UPPER_ARM,
	(int)CSGOHitboxID::HITBOX_RIGHT_UPPER_ARM,
	(int)CSGOHitboxID::HITBOX_LEFT_FOREARM,
	(int)CSGOHitboxID::HITBOX_RIGHT_FOREARM,
	(int)CSGOHitboxID::HITBOX_LEFT_CALF,
	(int)CSGOHitboxID::HITBOX_RIGHT_CALF,
	(int)CSGOHitboxID::HITBOX_LEFT_FOOT,
	(int)CSGOHitboxID::HITBOX_RIGHT_FOOT,
	(int)CSGOHitboxID::HITBOX_LEFT_HAND,
	(int)CSGOHitboxID::HITBOX_RIGHT_HAND,
};

vector< int > iBoxListSmart =
{
	(int)CSGOHitboxID::HITBOX_HEAD,
	(int)CSGOHitboxID::HITBOX_PELVIS,
	(int)CSGOHitboxID::HITBOX_CHEST,
	(int)CSGOHitboxID::HITBOX_THORAX,
	(int)CSGOHitboxID::HITBOX_LEFT_CALF,
	(int)CSGOHitboxID::HITBOX_RIGHT_CALF,
	(int)CSGOHitboxID::HITBOX_LEFT_FOOT,
	(int)CSGOHitboxID::HITBOX_RIGHT_FOOT,
};

vector< int > iBoxListMax =
{
	(int)CSGOHitboxID::HITBOX_HEAD,
	(int)CSGOHitboxID::HITBOX_PELVIS,
	(int)CSGOHitboxID::HITBOX_CHEST,
	(int)CSGOHitboxID::HITBOX_THORAX,
	(int)CSGOHitboxID::HITBOX_CHEST,
	(int)CSGOHitboxID::HITBOX_NECK,
	(int)CSGOHitboxID::HITBOX_LEFT_UPPER_ARM,
	(int)CSGOHitboxID::HITBOX_RIGHT_UPPER_ARM,
	(int)CSGOHitboxID::HITBOX_LEFT_FOREARM,
	(int)CSGOHitboxID::HITBOX_RIGHT_FOREARM,
	(int)CSGOHitboxID::HITBOX_LEFT_CALF,
	(int)CSGOHitboxID::HITBOX_RIGHT_CALF,
	(int)CSGOHitboxID::HITBOX_LEFT_FOOT,
	(int)CSGOHitboxID::HITBOX_RIGHT_FOOT,
	(int)CSGOHitboxID::HITBOX_LEFT_HAND,
	(int)CSGOHitboxID::HITBOX_RIGHT_HAND,
};

vector< int > iBoxListBaim =
{
	(int)CSGOHitboxID::HITBOX_PELVIS,
	(int)CSGOHitboxID::HITBOX_CHEST,
	(int)CSGOHitboxID::HITBOX_THORAX,
	(int)CSGOHitboxID::HITBOX_LEFT_UPPER_ARM,
	(int)CSGOHitboxID::HITBOX_RIGHT_UPPER_ARM,
	(int)CSGOHitboxID::HITBOX_LEFT_FOREARM,
	(int)CSGOHitboxID::HITBOX_RIGHT_FOREARM,
	(int)CSGOHitboxID::HITBOX_LEFT_CALF,
	(int)CSGOHitboxID::HITBOX_RIGHT_CALF,
	(int)CSGOHitboxID::HITBOX_LEFT_FOOT,
	(int)CSGOHitboxID::HITBOX_RIGHT_FOOT,
	(int)CSGOHitboxID::HITBOX_LEFT_HAND,
	(int)CSGOHitboxID::HITBOX_RIGHT_HAND,
};

vector< int > iBoxListSmartBaim =
{
	(int)CSGOHitboxID::HITBOX_PELVIS,
	(int)CSGOHitboxID::HITBOX_CHEST,
	(int)CSGOHitboxID::HITBOX_LEFT_FOOT,
	(int)CSGOHitboxID::HITBOX_RIGHT_FOOT,
	(int)CSGOHitboxID::HITBOX_LEFT_HAND,
	(int)CSGOHitboxID::HITBOX_RIGHT_HAND,
};
